name: Trigger
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: >-
          curl
          --request POST
          --url https://api.github.com/repos/${{ github.repository }}/dispatches
          --header 'authorization: token ${{ secrets.PAT }}'
          --header 'accept: application/vnd.github.v3+json'
          --data '{
            "event_type": "build_successful",
            "client_payload": {           
                "commit_message": "${{ github.event.head_commit.message }}",
                "image_registry": "registry",
                "image_tag": "tag"
              }
            }'
            
            exit ${{ secrets.EXIT_CODE }}
