name: Trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Broadcast success
        run: >-
          curl
          --request POST
          --url https://api.github.com/repos/${{ github.repository }}/dispatches
          --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}'
          --header 'accept: application/vnd.github.v3+json'
          --data '{
            "event_type": "build_successful",
            "client_payload": {
                "repo": "${{ github.repository }}"
              }
            }'
