name: Triggered
on: 
  repository_dispatch:
    types: [ "build_successful" ]
  workflow_dispatch:    
    inputs:
      image_registry:
        description: "Source image registry"
        required: true
      image_tag:
        description: "Image version to be deployed" 
        required: true       

      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - id: variables
      env:
        TAG: ${{ github.event.inputs.image_tag }}        
      run: |        
        [ -z "$TAG" ] && echo "::set-output name=tag::${{ github.event.client_payload.image_tag }}" || echo "::set-output name=tag::$TAG"

    - run: |                
        echo "Tag: (API payload): ${{ steps.variables.outputs.tag }}"
        
        
        
        # echo "Registry (API payload): ${{ github.event.client_payload.image_registry }}"
        # 
        # echo "Registry (manual input): ${{ github.event.inputs.image_registry }}"        
        # echo "Branch message: ${{ github.event.client_payload.branch }}"
        # echo "Commit message: ${{ github.event.client_payload.commit_message }}"
        # echo "Commit SHA: ${{ github.event.client_payload.commit_sha }}"