name: Triggered
on: 
  workflow_dispatch:
    types: [ "build_successful" ]
    inputs:
      image_registry:
        description: "Source image registry"
        required: true
      image_tag:
        description: "Image version to be deployed" 
        required: true
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |                
        echo "Registry (API payload): ${{ github.event.client_payload.image_registry }}"
        echo "Tag: (API payload): ${{ github.event.client_payload.image_tag }}"
        echo "Registry (manual input): ${{ github.event.inputs.image_registry }}"
        echo "Tag (manual input): ${{ github.event.inputs.image_tag }}"