name: Triggered
on: 
  repository_dispatch:
    types: [ "build_successful" ]
  workflow_dispatch:    
    inputs:
      image_registry:
        description: "Source image registry"
        required: true
      image_tag:
        description: "Image version to be deployed" 
        required: true       
env:
  variable: ""

      
jobs:
  set-variables:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.variables.outputs.version }}

    steps:

    - name: Set variables      
      id: variables
      env:
        REGISTRY: ${{ github.event.inputs.image_registry }}
        TAG: ${{ github.event.inputs.image_tag }}
      run: |-        
        [ -z "$REGISTRY" ] && REGISTRY=${{ github.event.client_payload.image_registry }}
        [ -z "$TAG" ] && TAG=${{ github.event.client_payload.image_tag }}        
        echo "::set-output name=version::[\""$REGISTRY:$TAG"\"]"
        echo $REGISTRY:$TAG
        variable=asd

  payload:
    needs: set-variables
    runs-on: ubuntu-latest

    steps:
      - run: |-
        echo ${{ needs.set-variables.outputs.version }}
        echo $variable

  version:
    needs: set-variables
    runs-on: ubuntu-latest

    strategy:    
      matrix:
        version: ${{ fromJson(needs.set-variables.outputs.version) }}

    steps:
      - run: echo ${{ needs.set-variables.outputs.version }}