name: Triggered
on: 
  repository_dispatch:
    types: [ "build_successful" ]
  workflow_dispatch:    
    inputs:
      image_registry:
        description: "Source image registry"
        required: true
      image_tag:
        description: "Image version to be deployed" 
        required: true       

      
jobs:
  set-variables:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.variables.outputs.version }}

    steps:

    - name: Set variables
      id: variables
      env:
        REGISTRY: ${{ github.event.inputs.image_registry }}
        TAG: ${{ github.event.inputs.image_tag }}
      run: |        
        [ -z "$REGISTRY" ] && echo "::set-output name=registry::${{ github.event.client_payload.image_registry }}" || echo "::set-output name=registry::$REGISTRY"
        [ -z "$TAG" ] && echo "::set-output name=tag::${{ github.event.client_payload.image_tag }}" || echo "::set-output name=tag::$TAG"
        echo "::set-output name=version::["$REGISTRY:$TAG"]"

  version:
    needs: set-variables
    runs-on: ubuntu-latest

    # strategy:    
    #   matrix:
    #     package: ${{ fromJson(needs.set-variables.outputs.version) }}

    steps:
      - run: echo ${{ needs.set-variables.outputs.version) }}