name: Triggered
on: 
  repository_dispatch:
    types: [ "build_successful" ]
    inputs:
      image_registry:
        description: "Source image registry"
        required: true
      image_tag:
        description: "Image version to be deployed" 
        required: true
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Registry: ${{ github.event.inputs.image_registry }}"
        echo "Registry: ${{ github.event.inputs.image_registry }}"
        echo "Registry: ${{ github.event.client_payload.repo }}"
        echo "Registry: ${{ github.event.client_payload.image_registry }}"
        echo "Registry: ${{ github.event.client_payload.image_tag }}"